name: Aurora Pipeline – PR Data Updates

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  scrape-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Prepare folders
        run: |
          mkdir -p data/input data/coa data/procurement data/comelec data/courts data/dbm saln_meta tools

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rvest any::dplyr any::stringr any::janitor
            any::readr any::purrr any::jsonlite any::digest
            any::httr any::lubridate

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pydantic

      # Run scrapers (best-effort)
      - run: Rscript R/fetch_ph_legislators.R
        name: Legislators
        continue-on-error: true
      - run: Rscript R/fetch_saln_metadata.R
        name: SALN
        continue-on-error: true
      - run: Rscript R/fetch_pnp_data.R
        name: PNP
        continue-on-error: true
      - run: Rscript R/coa_findings.R
        name: COA
        continue-on-error: true
      - run: Rscript R/philgeps_awards.R
        name: PhilGEPS
        continue-on-error: true
      - run: Rscript R/comelec_soce.R
        name: COMELEC
        continue-on-error: true
      - run: Rscript R/court_cases.R
        name: Courts
        continue-on-error: true
      - run: Rscript R/dbm_releases.R
        name: DBM
        continue-on-error: true

      - name: Emit risk events
        env:
          AURORA_API_URL: ${{ secrets.AURORA_API_URL }}
          AURORA_API_TOKEN: ${{ secrets.AURORA_API_TOKEN }}
        run: python tools/emit_risk.py || echo "[emit_risk] skipped"
        continue-on-error: true

      - name: Create PR with data updates
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[auto] Update data (Aurora pipeline)"
          branch: data/auto-update
          branch-suffix: timestamp
          delete-branch: true
          signoff: true
          committer: github-actions <actions@github.com>
          author: github-actions <actions@github.com>
          title: "Automated data update"
          body: |
            Automated data updates produced by the Aurora pipeline.
            Review and merge to apply changes.
          labels: data-update, automated
          add-paths: |
            data/**
            saln_meta/**

      - name: Debug info on failure
        if: failure()
        run: |
          Rscript -e 'sessionInfo()' || true
          git remote -v || true
          ls -R || true
