- name: Trigger Aurora Backend (via ngrok)
  run: |
    curl -X POST https://a4d89c2af3d5.ngrok-free.app/ops/aurora/dispatch \
      -H "Content-Type: application/json" \
      -d '{"branch": "main"}'
