name: Aurora Pipeline – PR Data Updates

on:
  schedule:
    - cron: '0 1 * * *'   # daily at 01:00 UTC
  workflow_dispatch:       # manual Run workflow button

permissions:
  contents: write
  pull-requests: write

jobs:
  scrape-and-pr:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # disable default token
          fetch-depth: 0

      # Configure git (prevents exit 128/dubious ownership)
      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      # Prep folders
      - name: Prepare folders
        run: |
          mkdir -p data/input data/coa data/procurement data/comelec data/courts data/dbm saln_meta tools

      # R setup
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rvest
            any::dplyr
            any::stringr
            any::janitor
            any::readr
            any::purrr
            any::jsonlite
            any::digest
            any::httr
            any::lubridate

      # Python setup
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pydantic

      # Run scrapers (best-effort, don’t fail whole job)
      - name: Legislators
        run: Rscript R/fetch_ph_legislators.R
        continue-on-error: true

      - name: SALN metadata
        run: Rscript R/fetch_saln_metadata.R
        continue-on-error: true

      - name: PNP
        run: Rscript R/fetch_pnp_data.R
        continue-on-error: true

      - name: COA
        run: Rscript R/coa_findings.R
        continue-on-error: true

      - name: PhilGEPS
        run: Rscript R/philgeps_awards.R
        continue-on-error: true

      - name: COMELEC
        run: Rscript R/comelec_soce.R
        continue-on-error: true

      - name: Courts
        run: Rscript R/court_cases.R
        continue-on-error: true

      - name: DBM
        run: Rscript R/dbm_releases.R
        continue-on-error: true

      # Risk events (skip if API not configured)
      - name: Emit risk events
        env:
          AURORA_API_URL: ${{ secrets.AURORA_API_URL }}
          AURORA_API_TOKEN: ${{ secrets.AURORA_API_TOKEN }}
        run: python tools/emit_risk.py || echo "[emit_risk] skipped"
        continue-on-error: true

      # Always create/update PR (no git push)
      - name: Create pull request with data updates
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[auto] Update data (Legislators/SALN/PNP/COA/PhilGEPS/COMELEC/Courts/DBM)"
          branch: data/auto-update
          branch-suffix: timestamp
          delete-branch: true
          signoff: true
          committer: github-actions <actions@github.com>
          author: github-actions <actions@github.com>
          title: "Automated data update"
          body: |
            This PR contains automated data updates produced by the Aurora pipeline.
            Review diffs and merge when ready.
          labels: data-update, automated
          add-paths: |
            data/**
            saln_meta/**

      # Debug info if failure
      - name: Session info on failure
        if: failure()
        run: |
          Rscript -e 'sessionInfo()' || true
          git remote -v || true
          ls -R || true
