name: Aurora Pipeline – PR Data Updates

on:
  schedule:
    - cron: "0 * * * *"        # Runs every hour
  workflow_dispatch:           # Enables manual trigger

jobs:
  aurora_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Packages
        run: |
          Rscript -e 'install.packages(c("httr", "jsonlite", "dplyr", "rvest"))'

      - name: Run Aurora Scraper
        run: |
          Rscript R/scrape_all.R

      - name: Trigger Aurora Backend (via ngrok)
        run: |
          curl -X POST https://a4d89c2af3d5.ngrok-free.app/ops/aurora/dispatch \
            -H "Content-Type: application/json" \
            -d '{"branch": "main"}'
