nm <- names(df)
name_col <- if ("name" %in% nm) "name" else nm[1]
party_col <- if ("party" %in% nm) "party" else if ("political_party" %in% nm) "political_party" else NA_character_
dist_col  <- if ("district" %in% nm) "district" else if ("district_info" %in% nm) "district_info" else NA_character_

df |>
  tibble::tibble(
    name          = stringr::str_squish(as.character(df[[name_col]])),
    party         = if (!is.na(party_col)) stringr::str_squish(as.character(df[[party_col]])) else NA_character_,
    district_info = if (!is.na(dist_col))  stringr::str_squish(as.character(df[[dist_col]]))  else NA_character_,
    chamber       = "house",
    source        = "wikipedia",
    official_profile_url = NA_character_,
    last_updated  = Sys.Date()
  )
