name: Auto Scrape Legislators, SALN, and PNP

on:
  schedule:
    - cron: '0 1 * * *'  # every day at 01:00 UTC
  workflow_dispatch:

jobs:
  scrape-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rvest","dplyr","stringr","janitor","readr","purrr","jsonlite"))'

      # --- Legislators ---
      - name: Run legislator scraper
        run: |
          Rscript R/fetch_ph_legislators.R

      - name: Commit legislator data
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add data/philippines_*.csv
          git commit -m "[auto] Update legislator data" || echo "No legislator changes to commit"
          git push

      # --- SALN Metadata ---
      - name: Run SALN metadata generator
        run: |
          Rscript R/fetch_saln_metadata.R

      - name: Commit SALN metadata
        run: |
          git add saln_meta/*.json
          git commit -m "[auto] Update SALN metadata" || echo "No SALN changes to commit"
          git push

      # --- PNP Data ---
      - name: Run PNP scraper
        run: |
          Rscript R/fetch_pnp_data.R

      - name: Commit PNP data
        run: |
          git add data/pnp/*.csv
          git commit -m "[auto] Update PNP data" || echo "No PNP changes to commit"
          git push
